---
apiVersion: v1
kind: Service
metadata:
  name: check-web-svc
  namespace: check
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: check-web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-web-dep
  namespace: check
spec:
  selector:
    matchLabels:
      app: check-web-svc
  template:
    metadata:
      labels:
        app: check-web-svc
    spec:
      containers:
        - image: nginx:stable-alpine3.17-slim
          name: check-web-svc
          ports:
            - containerPort: 80
              name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: check-cert
  #referenced Secret must exist in the namespace of the istio-ingressgateway
  namespace: istio-system 
spec:
  secretName: check-cert
  commonName: check.manimaul.com 
  dnsNames:
  - check.manimaul.com 
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod 
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: check-gateway 
  namespace: check
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - check.manimaul.com 
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - check.manimaul.com 
    tls:
      mode: SIMPLE
      #referenced Secret must exist in the namespace of the istio-ingressgateway
      credentialName: check-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: check-vsvc 
  namespace: check
spec:
  hosts:
  - check.manimaul.com
  gateways:
  - check-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: check-web-svc
        port:
          number: 8080
---

