apiVersion: v1
kind: Namespace
metadata:
  name: check
---
apiVersion: v1
kind: Service
metadata:
  name: check-web-svc
  namespace: check
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: check-web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-web-dep
  namespace: check
spec:
  selector:
    matchLabels:
      app: check-web-svc
  template:
    metadata:
      labels:
        app: check-web-svc
    spec:
      containers:
        - image: nginx
          name: check-web-svc
          ports:
            - containerPort: 80
              name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: check-cert
  namespace: check
spec:
  secretName: check-cert
  commonName: check.manimaul.com
  dnsNames:
    - check.manimaul.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkingress
  namespace: check
spec:
  ingressClassName: haproxy
  rules:
    - host: check.manimaul.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: check-web-svc
                port:
                  number: 80
  tls:
    - hosts:
        - check.manimaul.com
      secretName: check-cert
